id = "mangoes-theme"
name = "Mangoes"
version = "0.1.1"
schema_version = 1
authors = ["fangorodev"]
description = "A theme that tastes like its name"
repository = "https://github.com/fangorodev/zed-mangoes"
